#include "UiColors.h"

//包含全部基本类型数据结构，以在开发阶段测试是否有编译错误等
#include "duilib/Core/UiColor.h"
#include "duilib/Core/UiFont.h"
#include "duilib/Core/UiRect.h"
#include "duilib/Core/UiSize.h"
#include "duilib/Core/UiPoint.h"

namespace ui 
{
namespace UiColors
{
    /** 常见颜色值，对应的字符串常量
    */
    void GetUiColorsString(std::vector<std::pair<std::wstring, int32_t>>& uiColors)
    {
        uiColors = {
                    {L"AliceBlue",UiColors::AliceBlue},
                    {L"AntiqueWhite",UiColors::AntiqueWhite},
                    {L"Aqua",UiColors::Aqua},
                    {L"Aquamarine",UiColors::Aquamarine},
                    {L"Azure",UiColors::Azure},
                    {L"Beige",UiColors::Beige},
                    {L"Bisque",UiColors::Bisque},
                    {L"Black",UiColors::Black},
                    {L"BlanchedAlmond",UiColors::BlanchedAlmond},
                    {L"Blue",UiColors::Blue},
                    {L"BlueViolet",UiColors::BlueViolet},
                    {L"Brown",UiColors::Brown},
                    {L"BurlyWood",UiColors::BurlyWood},
                    {L"CadetBlue",UiColors::CadetBlue},
                    {L"Chartreuse",UiColors::Chartreuse},
                    {L"Chocolate",UiColors::Chocolate},
                    {L"Coral",UiColors::Coral},
                    {L"CornflowerBlue",UiColors::CornflowerBlue},
                    {L"Cornsilk",UiColors::Cornsilk},
                    {L"Crimson",UiColors::Crimson},
                    {L"Cyan",UiColors::Cyan},
                    {L"DarkBlue",UiColors::DarkBlue},
                    {L"DarkCyan",UiColors::DarkCyan},
                    {L"DarkGoldenrod",UiColors::DarkGoldenrod},
                    {L"DarkGray",UiColors::DarkGray},
                    {L"DarkGreen",UiColors::DarkGreen},
                    {L"DarkKhaki",UiColors::DarkKhaki},
                    {L"DarkMagenta",UiColors::DarkMagenta},
                    {L"DarkOliveGreen",UiColors::DarkOliveGreen},
                    {L"DarkOrange",UiColors::DarkOrange},
                    {L"DarkOrchid",UiColors::DarkOrchid},
                    {L"DarkRed",UiColors::DarkRed},
                    {L"DarkSalmon",UiColors::DarkSalmon},
                    {L"DarkSeaGreen",UiColors::DarkSeaGreen},
                    {L"DarkSlateBlue",UiColors::DarkSlateBlue},
                    {L"DarkSlateGray",UiColors::DarkSlateGray},
                    {L"DarkTurquoise",UiColors::DarkTurquoise},
                    {L"DarkViolet",UiColors::DarkViolet},
                    {L"DeepPink",UiColors::DeepPink},
                    {L"DeepSkyBlue",UiColors::DeepSkyBlue},
                    {L"DimGray",UiColors::DimGray},
                    {L"DodgerBlue",UiColors::DodgerBlue},
                    {L"Firebrick",UiColors::Firebrick},
                    {L"FloralWhite",UiColors::FloralWhite},
                    {L"ForestGreen",UiColors::ForestGreen},
                    {L"Fuchsia",UiColors::Fuchsia},
                    {L"Gainsboro",UiColors::Gainsboro},
                    {L"GhostWhite",UiColors::GhostWhite},
                    {L"Gold",UiColors::Gold},
                    {L"Goldenrod",UiColors::Goldenrod},
                    {L"Gray",UiColors::Gray},
                    {L"Green",UiColors::Green},
                    {L"GreenYellow",UiColors::GreenYellow},
                    {L"Honeydew",UiColors::Honeydew},
                    {L"HotPink",UiColors::HotPink},
                    {L"IndianRed",UiColors::IndianRed},
                    {L"Indigo",UiColors::Indigo},
                    {L"Ivory",UiColors::Ivory},
                    {L"Khaki",UiColors::Khaki},
                    {L"Lavender",UiColors::Lavender},
                    {L"LavenderBlush",UiColors::LavenderBlush},
                    {L"LawnGreen",UiColors::LawnGreen},
                    {L"LemonChiffon",UiColors::LemonChiffon},
                    {L"LightBlue",UiColors::LightBlue},
                    {L"LightCoral",UiColors::LightCoral},
                    {L"LightCyan",UiColors::LightCyan},
                    {L"LightGoldenrodYellow",UiColors::LightGoldenrodYellow},
                    {L"LightGray",UiColors::LightGray},
                    {L"LightGreen",UiColors::LightGreen},
                    {L"LightPink",UiColors::LightPink},
                    {L"LightSalmon",UiColors::LightSalmon},
                    {L"LightSeaGreen",UiColors::LightSeaGreen},
                    {L"LightSkyBlue",UiColors::LightSkyBlue},
                    {L"LightSlateGray",UiColors::LightSlateGray},
                    {L"LightSteelBlue",UiColors::LightSteelBlue},
                    {L"LightYellow",UiColors::LightYellow},
                    {L"Lime",UiColors::Lime},
                    {L"LimeGreen",UiColors::LimeGreen},
                    {L"Linen",UiColors::Linen},
                    {L"Magenta",UiColors::Magenta},
                    {L"Maroon",UiColors::Maroon},
                    {L"MediumAquamarine",UiColors::MediumAquamarine},
                    {L"MediumBlue",UiColors::MediumBlue},
                    {L"MediumOrchid",UiColors::MediumOrchid},
                    {L"MediumPurple",UiColors::MediumPurple},
                    {L"MediumSeaGreen",UiColors::MediumSeaGreen},
                    {L"MediumSlateBlue",UiColors::MediumSlateBlue},
                    {L"MediumSpringGreen",UiColors::MediumSpringGreen},
                    {L"MediumTurquoise",UiColors::MediumTurquoise},
                    {L"MediumVioletRed",UiColors::MediumVioletRed},
                    {L"MidnightBlue",UiColors::MidnightBlue},
                    {L"MintCream",UiColors::MintCream},
                    {L"MistyRose",UiColors::MistyRose},
                    {L"Moccasin",UiColors::Moccasin},
                    {L"NavajoWhite",UiColors::NavajoWhite},
                    {L"Navy",UiColors::Navy},
                    {L"OldLace",UiColors::OldLace},
                    {L"Olive",UiColors::Olive},
                    {L"OliveDrab",UiColors::OliveDrab},
                    {L"Orange",UiColors::Orange},
                    {L"OrangeRed",UiColors::OrangeRed},
                    {L"Orchid",UiColors::Orchid},
                    {L"PaleGoldenrod",UiColors::PaleGoldenrod},
                    {L"PaleGreen",UiColors::PaleGreen},
                    {L"PaleTurquoise",UiColors::PaleTurquoise},
                    {L"PaleVioletRed",UiColors::PaleVioletRed},
                    {L"PapayaWhip",UiColors::PapayaWhip},
                    {L"PeachPuff",UiColors::PeachPuff},
                    {L"Peru",UiColors::Peru},
                    {L"Pink",UiColors::Pink},
                    {L"Plum",UiColors::Plum},
                    {L"PowderBlue",UiColors::PowderBlue},
                    {L"Purple",UiColors::Purple},
                    {L"Red",UiColors::Red},
                    {L"RosyBrown",UiColors::RosyBrown},
                    {L"RoyalBlue",UiColors::RoyalBlue},
                    {L"SaddleBrown",UiColors::SaddleBrown},
                    {L"Salmon",UiColors::Salmon},
                    {L"SandyBrown",UiColors::SandyBrown},
                    {L"SeaGreen",UiColors::SeaGreen},
                    {L"SeaShell",UiColors::SeaShell},
                    {L"Sienna",UiColors::Sienna},
                    {L"Silver",UiColors::Silver},
                    {L"SkyBlue",UiColors::SkyBlue},
                    {L"SlateBlue",UiColors::SlateBlue},
                    {L"SlateGray",UiColors::SlateGray},
                    {L"Snow",UiColors::Snow},
                    {L"SpringGreen",UiColors::SpringGreen},
                    {L"SteelBlue",UiColors::SteelBlue},
                    {L"Tan",UiColors::Tan},
                    {L"Teal",UiColors::Teal},
                    {L"Thistle",UiColors::Thistle},
                    {L"Tomato",UiColors::Tomato},
                    {L"Transparent",UiColors::Transparent},
                    {L"Turquoise",UiColors::Turquoise},
                    {L"Violet",UiColors::Violet},
                    {L"Wheat",UiColors::Wheat},
                    {L"White",UiColors::White},
                    {L"WhiteSmoke",UiColors::WhiteSmoke},
                    {L"Yellow",UiColors::Yellow},
                    {L"YellowGreen",UiColors::YellowGreen}
                    };
    }
}// namespace UiColors
} // namespace ui

